using System.Runtime.CompilerServices;
using UnityEngine;

public class HatManager : MonoBehaviour //All of this code was generated by ChatGPT. Look into and design properly
{
    public static HatManager instance;
    public GameObject[] hats;
    private int currentHatIndex = 0;
    private void Awake()
    {
        instance = this;
    }
    private void Start()
    {
        LoadHatSelection();
        UpdateHatVisibility();
    }
    public void UpdateHats()
    {
        //GameManager.instance.AddHatRule(hats); 
    }
    private void UpdateHatVisibility()
    {
        for (int i = 0; i < hats.Length; i++)
        {
            hats[i].SetActive(i == currentHatIndex);
        }
    }
    private void SaveHatSelection()
    {
        PlayerPrefs.SetInt("SelectedHatIndex", currentHatIndex);
        PlayerPrefs.Save();
    }
    private void LoadHatSelection()
    {
        currentHatIndex = PlayerPrefs.GetInt("SelectedHatIndex", 0);
    }
}
